[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.9.1"
bincode = "1.3.3"
serde = { version = "1.0.145", features = ["derive"] }
flate2 = "1.0.24"
